name: Rocket.AutoInstaller

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/Rocket.AutoInstaller.yaml'
      - 'Rocket.AutoInstaller/**'
  pull_request:
    paths:
      - '.github/workflows/Rocket.AutoInstaller.yaml'
      - 'Rocket.AutoInstaller/**'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        name: Setup .NET
        with:
          dotnet-version: 8.x

      - name: Build Project
        uses: ./.github/actions/project-build
        id: project-build
        with:
          project_path: Rocket.AutoInstaller
          nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
          nuget_push: false
          github_token: ${{ secrets.PAT }}

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip artifacts
        run: "cd ./Rocket.AutoInstaller/bin/Release/net461/linux-x64/Rocket.AutoInstaller && zip -qq -r ./Rocket.AutoInstaller.zip *"

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Rocket.AutoInstaller.zip
          path: "./Rocket.AutoInstaller/bin/Release/net461/linux-x64/Rocket.AutoInstaller/Rocket.AutoInstaller.zip"
          if-no-files-found: error

      - name: Create Release
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        uses: ncipollo/release-action@v1.14.0
        with:
          name: RocketModFix Release v${{ steps.project-build.outputs.version }}
          tag: ${{ steps.project-build.outputs.version }}
          artifacts: "./Rocket.AutoInstaller/bin/Release/net461/linux-x64/Rocket.AutoInstaller/Rocket.AutoInstaller.Module.zip"
          token: ${{ secrets.PAT }}
          prerelease: ${{ steps.project-build.outputs.is_prerelease }}
          allowUpdates: true
          draft: true