name: RocketModFix.Module

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/RocketModFix.Module.yaml'
      - 'Rocket/**'
      - 'Rocket.Unturned/**'
  pull_request:
    paths:
      - '.github/workflows/RocketModFix.Module.yaml'
      - 'Rocket/**'
      - 'Rocket.Unturned/**'

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v3
        name: Setup .NET
        with:
          dotnet-version: 8.x

      - name: Build Project
        uses: ./.github/actions/project-build
        id: project-build
        with:
          project_path: Rocket.Unturned
          target_framework: net461
          nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
          nuget_push: true
          github_token: ${{ secrets.PAT }}

      - name: Install zip
        run: sudo apt-get install zip

      - name: Zip artifacts
        run: "cd ./Rocket.Unturned/bin/Release/net461/linux-x64/Rocket.Unturned && zip -qq -r ./Rocket.Unturned.Module.zip *"

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Rocket.Unturned.Module.zip
          path: "./Rocket.Unturned/bin/Release/net461/linux-x64/Rocket.Unturned/Rocket.Unturned.Module.zip"
          if-no-files-found: error

      - name: Create Release
        if: github.event_name == 'create' && github.event.ref_type == 'tag'
        uses: ncipollo/release-action@v1.14.0
        with:
          name: RocketModFix Release v${{ steps.project-build.outputs.version }}
          tag: v${{ steps.project-build.outputs.version }}
          artifacts: "./Rocket.Unturned/bin/Release/net461/linux-x64/Rocket.Unturned/Rocket.Unturned.Module.zip"
          token: ${{ secrets.PAT }}
          prerelease: ${{ steps.project-build.outputs.is_prerelease }}
          allowUpdates: true
          generateReleaseNotes: true
          draft: true